### ISSUE TITLE
Feature Request: Subcommand completion on ensembles

### ISSUE THREAD

**Issue by gwlester** [suewonjp/tclsh-wrapper#3]
Attempting a completions on an ensemble subcommand results in the list of commands that meet the partially typed word.  It would be nice if it displayed the list of subcommands.

For example:
`namespace en<Tab>`
should complete to:
`namespace ensemble`

**Comment by suewonjp** [comment]
https://github.com/suewonjp/tclsh-wrapper#tea-keyword-completion

```
For another example, inserting the following lines into the configuration file will let you just type s*tol<TAB> for string tblower.

    TclReadLine::keyword {string tolower}
    TclReadLine::keyword {string totitle}
    TclReadLine::keyword {string toupper}
    TclReadLine::keyword {string trim}
    TclReadLine::keyword {string trimleft}
    TclReadLine::keyword {string trimright}
```

I think the existing approach as above can accomplish similar results.

I've considered the approach you suggest once and I know it looks standard and intuitive, but the implementation burden was not quite small, at least to me.

Let me think about it, but remember that the existing approach is also quite useful. Please, try it unless you have yet.

**Comment by gwlester** [comment]
You can use [namespace ensemble configure] to query the subcomands.
I'm traveling today and will attempt to send you more details on about 12 hours.


Happy Connecting. Sent from my Sprint Samsung Galaxy S® 5

-------- Original message --------

**Comment by suewonjp** [comment]
Please, pull https://github.com/suewonjp/tclsh-wrapper/tree/v1.4rc and check it out

**Comment by suewonjp** [comment]
closing this
