### ISSUE TITLE
multiline behavior?

### ISSUE THREAD

**Issue by jsuntheimer72** [suewonjp/tclsh-wrapper#7]
![2018-02-12-144939_400x187_escrotum](https://user-images.githubusercontent.com/34604575/36117448-a9fe9250-1007-11e8-95e8-5386ac26a516.png)

This is the out-of-the-box experience of opening a {, hitting enter 3 times, then closing the brace.  The cursor remains on the top line, moving one space to the right on each keypress.
This is occurring on a barely configured xterm, with no customization of prompts in tclsh-wrapper or anything like that.

**Comment by suewonjp** [comment]
Let me confess I didn't consider multiline interface at all...

So the current multiline behavior is really crazy.

I'll support that.

**Comment by suewonjp** [comment]
Can you pull https://github.com/suewonjp/tclsh-wrapper/tree/v1.4rc and check it out?

Also, you can copy and paste multiline code snippets if your terminal can communicate with the system clipboard.

**Comment by jsuntheimer72** [comment]
Fantastic!  Thanks!
