### ISSUE TITLE
Feature Inquery: namespace path {::tcl::mathop ::tcl::mathfunc}

### ISSUE THREAD

**Issue by jsuntheimer72** [suewonjp/tclsh-wrapper#8]
I think this makes for a pretty sweet & convenient repl/shell environment.

namespace path {::tcl::mathop ::tcl::mathfunc}
\+ 1 2 3 
6
 rand 
0.7885820026456295
 in foo {foo bar baz}
1

**Comment by suewonjp** [comment]
Yeh... that looks cool.

**Comment by suewonjp** [comment]
Can you pull https://github.com/suewonjp/tclsh-wrapper/tree/v1.4rc and check it out?

**Comment by jsuntheimer72** [comment]
Works a treat!
