### ISSUE TITLE
Code organization

### ISSUE THREAD

**Issue by jsuntheimer72** [suewonjp/tclsh-wrapper#9]
Hi!

So currently all tclsh-wrapper commands are in bag-of-procs namespace.  There are only so many, the complexity is not insurmountable or anything, but to dip your toe into tclsh-wrapper is swim in it's pool.  There are two obvious 8.6 solutions: child namespaces and tcloo.  
Although I want to justify this at length, I won't, instead when next you hear from me, I am going to present a tcloo-ified tclsh-wrapper, and we all can discuss it as a proposal.  If you prefer to use namespaces, I don't mind at all if this effort is ultimately in vain :)

**Comment by suewonjp** [comment]
Thanks.

I don't prefer namespaces.  Feel free to apply tcloo to the existing code. 

I'm not familiar with tcloo, though, I don't mind learning it.

**Comment by jsuntheimer72** [comment]
closing this
